# original author:
# https://github.com/victoriadrake/victoriadrake

name: updater-readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 11 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🍳 Shake & bake README
        run: |
          cd ${GITHUB_WORKSPACE}/
          node api-codewars.mjs
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "[AUTO] Update dynamic content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git